//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aguinaldo
    {
        public int idAguinaldo { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int anio { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fecha_calculo { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
