//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class AportesSeguridadSocial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AportesSeguridadSocial()
        {
            this.DetalleAporte = new HashSet<DetalleAporte>();
        }
    
        public int idAporte { get; set; }
        public string nombre { get; set; }
        public decimal porcentaje { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleAporte> DetalleAporte { get; set; }
    }
}
