//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int idAsistencia { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
        public bool es_justificada { get; set; }
        public Nullable<System.TimeSpan> hora_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
        public decimal horas_trabajadas { get; set; }
        public decimal horas_netas { get; set; }
        public decimal horas_extra { get; set; }
        public bool tiene_tardia { get; set; }
        public int minutos_tardia { get; set; }
        public string observacion { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
