//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaGeneral
    {
        public int idAuditoria { get; set; }
        public string tabla { get; set; }
        public string idRegistro { get; set; }
        public string accion { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string detalle { get; set; }
    }
}
