//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaGeneral
    {
        public int idAuditoria { get; set; }
        public string tabla { get; set; }
        public string idRegistro { get; set; }
        public string accion { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string detalle { get; set; }
    }
}
