//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int idBitacora { get; set; }
        public int Credencial_idCredencial { get; set; }
        public string accion { get; set; }
        public System.DateTime fecha { get; set; }
        public string ip_origen { get; set; }
        public string descripcion { get; set; }
    
        public virtual Credencial Credencial { get; set; }
    }
}
