//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int idBitacora { get; set; }
        public int Credencial_idCredencial { get; set; }
        public string accion { get; set; }
        public System.DateTime fecha { get; set; }
        public string ip_origen { get; set; }
        public string descripcion { get; set; }
    
        public virtual Credencial Credencial { get; set; }
    }
}
