//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonificacion()
        {
            this.HistorialBonificacion = new HashSet<HistorialBonificacion>();
        }
    
        public int idBonificacion { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public string tipo { get; set; }
        public decimal monto { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public string estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialBonificacion> HistorialBonificacion { get; set; }
    }
}
