//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credencial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credencial()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Empleado = new HashSet<Empleado>();
            this.SesionUsuario = new HashSet<SesionUsuario>();
        }
    
        public int idCredencial { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int Rol_idRol { get; set; }
        public bool requiere_cambio { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_cambio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SesionUsuario> SesionUsuario { get; set; }
    }
}
