//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleRenta()
        {
            this.DetalleNomina = new HashSet<DetalleNomina>();
        }
    
        public int idDetalleRenta { get; set; }
        public int TramosParametrosRenta_idTramosParametrosRenta { get; set; }
        public decimal base_calculo { get; set; }
        public decimal monto_impuesto { get; set; }
        public string observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNomina> DetalleNomina { get; set; }
        public virtual TramosParametrosRenta TramosParametrosRenta { get; set; }
    }
}
