//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAporte
    {
        public int idDetalleAporte { get; set; }
        public int Aporte_idAporte { get; set; }
        public int DetalleNomina_idDetalleNomina { get; set; }
        public decimal monto { get; set; }
    
        public virtual AportesSeguridadSocial AportesSeguridadSocial { get; set; }
        public virtual DetalleNomina DetalleNomina { get; set; }
    }
}
