//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAporte
    {
        public int idDetalleAporte { get; set; }
        public int Aporte_idAporte { get; set; }
        public int DetalleNomina_idDetalleNomina { get; set; }
        public decimal monto { get; set; }
    
        public virtual AportesSeguridadSocial AportesSeguridadSocial { get; set; }
        public virtual DetalleNomina DetalleNomina { get; set; }
    }
}
