//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleNomina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleNomina()
        {
            this.DetalleAporte = new HashSet<DetalleAporte>();
        }
    
        public int idDetalleNomina { get; set; }
        public int Nomina_idNomina { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int SalarioBrutoMensual_idSalarioBrutoMensual { get; set; }
        public Nullable<int> DetalleRenta_idDetalleRenta { get; set; }
        public decimal total_bonificaciones { get; set; }
        public decimal total_horas_extra { get; set; }
        public decimal total_deducciones { get; set; }
        public decimal total_percepciones { get; set; }
        public decimal salario_neto { get; set; }
        public System.DateTime fecha_calculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleAporte> DetalleAporte { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Nomina Nomina { get; set; }
        public virtual DetalleRenta DetalleRenta { get; set; }
        public virtual SalarioBrutoMensual SalarioBrutoMensual { get; set; }
    }
}
