//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoHorario
    {
        public int idEmpleadoHorario { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int HorarioSemanal_idHorarioSemanal { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual HorarioSemanal HorarioSemanal { get; set; }
    }
}
