//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Aguinaldo = new HashSet<Aguinaldo>();
            this.Ausencia = new HashSet<Ausencia>();
            this.Bonificacion = new HashSet<Bonificacion>();
            this.DetalleNomina = new HashSet<DetalleNomina>();
            this.Feriado = new HashSet<Feriado>();
            this.HoraExtra = new HashSet<HoraExtra>();
            this.Incapacidad = new HashSet<Incapacidad>();
            this.Liquidacion = new HashSet<Liquidacion>();
            this.Permiso = new HashSet<Permiso>();
            this.SalarioBrutoMensual = new HashSet<SalarioBrutoMensual>();
            this.Tardia = new HashSet<Tardia>();
            this.Vacaciones = new HashSet<Vacaciones>();
            this.EmpleadoHorario = new HashSet<EmpleadoHorario>();
            this.RegistroMarcacion = new HashSet<RegistroMarcacion>();
            this.Asistencia = new HashSet<Asistencia>();
            this.EvaluacionPersonal = new HashSet<EvaluacionPersonal>();
        }
    
        public int idEmpleado { get; set; }
        public int Persona_idPersona { get; set; }
        public int Credencial_idCredencial { get; set; }
        public int Puesto_idPuesto { get; set; }
        public int Jornada_idJornada { get; set; }
        public Nullable<int> Horario_idHorario { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public string estado { get; set; }
        public Nullable<int> Direccion_idDireccion { get; set; }
        public Nullable<int> HorarioSemanal_idHorarioSemanal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aguinaldo> Aguinaldo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ausencia> Ausencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonificacion> Bonificacion { get; set; }
        public virtual Credencial Credencial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNomina> DetalleNomina { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Jornada Jornada { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Puesto Puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feriado> Feriado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoraExtra> HoraExtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incapacidad> Incapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidacion> Liquidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permiso> Permiso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalarioBrutoMensual> SalarioBrutoMensual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tardia> Tardia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacaciones> Vacaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoHorario> EmpleadoHorario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroMarcacion> RegistroMarcacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual HorarioSemanal HorarioSemanal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPersonal> EvaluacionPersonal { get; set; }
    }
}
