//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPersonal
    {
        public int idEvaluacion { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int anio { get; set; }
        public byte semestre { get; set; }
        public decimal nota_puntualidad { get; set; }
        public decimal nota_calidad { get; set; }
        public decimal nota_trabajo_equipo { get; set; }
        public decimal nota_iniciativa { get; set; }
        public decimal nota_cumplimiento { get; set; }
        public decimal nota_final { get; set; }
        public string calificacion { get; set; }
        public string evaluador { get; set; }
        public string comentarios { get; set; }
        public System.DateTime fecha_evaluacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
