//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeriadoLaborado
    {
        public int idFeriadoLaborado { get; set; }
        public int feriado_id { get; set; }
        public decimal horas { get; set; }
        public Nullable<decimal> pago_extra { get; set; }
    
        public virtual Feriado Feriado { get; set; }
    }
}
