//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialBonificacion
    {
        public int idHistorialBonificacion { get; set; }
        public int bonificacion_id { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Bonificacion Bonificacion { get; set; }
    }
}
