//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialHoraExtra
    {
        public int idHistorialHoraExtra { get; set; }
        public int HoraExtra_idHoraExtra { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string accion { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual HoraExtra HoraExtra { get; set; }
    }
}
