//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialBonificacion
    {
        public int idHistorialBonificacion { get; set; }
        public int bonificacion_id { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Bonificacion Bonificacion { get; set; }
    }
}
