//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPermiso
    {
        public int idHistorialPermiso { get; set; }
        public int Permiso_idPermiso { get; set; }
        public int idUsuario { get; set; }
        public string accion { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Permiso Permiso { get; set; }
    }
}
