//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialVacaciones
    {
        public int idHistorialVacaciones { get; set; }
        public int Vacaciones_idVacaciones { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string accion { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Vacaciones Vacaciones { get; set; }
    }
}
