//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoraExtra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoraExtra()
        {
            this.HistorialHoraExtra = new HashSet<HistorialHoraExtra>();
            this.SolicitudHorasExtra = new HashSet<SolicitudHorasExtra>();
        }
    
        public int idHoraExtra { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int ClaseHoraExtra_idClaseHoraExtra { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal cantidad_horas { get; set; }
        public bool aprobado { get; set; }
    
        public virtual ClaseHoraExtra ClaseHoraExtra { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialHoraExtra> HistorialHoraExtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudHorasExtra> SolicitudHorasExtra { get; set; }
    }
}
