//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioSemanal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HorarioSemanal()
        {
            this.EmpleadoHorario = new HashSet<EmpleadoHorario>();
            this.Horario = new HashSet<Horario>();
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int idHorarioSemanal { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> Jornada_idJornada { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoHorario> EmpleadoHorario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
        public virtual Jornada Jornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
