//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incapacidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incapacidad()
        {
            this.Incapacidad1 = new HashSet<Incapacidad>();
        }
    
        public int idIncapacidad { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public string entidad { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public decimal porcentaje_pago { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public int TipoIncapacidad_idTipoIncapacidad { get; set; }
        public string numero_boleta { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<int> dias_incapacidad { get; set; }
        public string origen { get; set; }
        public bool es_prorroga { get; set; }
        public Nullable<int> incapacidad_origen_id { get; set; }
        public bool afecta_asistencia { get; set; }
        public string observaciones_rrhh { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual TipoIncapacidad TipoIncapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incapacidad> Incapacidad1 { get; set; }
        public virtual Incapacidad Incapacidad2 { get; set; }
    }
}
