//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public int idLiquidacion { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int TipoLiquidacion_idTipoLiquidacion { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal total_percepciones { get; set; }
        public decimal total_deducciones { get; set; }
        public decimal neto_pagar { get; set; }
        public string observaciones { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual TipoLiquidacion TipoLiquidacion { get; set; }
    }
}
