//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public int idLiquidacion { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int TipoLiquidacion_idTipoLiquidacion { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal total_percepciones { get; set; }
        public decimal total_deducciones { get; set; }
        public decimal neto_pagar { get; set; }
        public string observaciones { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual TipoLiquidacion TipoLiquidacion { get; set; }
    }
}
