//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_NominaEntities : DbContext
    {
        public BD_NominaEntities()
            : base("name=BD_NominaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aguinaldo> Aguinaldo { get; set; }
        public virtual DbSet<AportesSeguridadSocial> AportesSeguridadSocial { get; set; }
        public virtual DbSet<AuditoriaGeneral> AuditoriaGeneral { get; set; }
        public virtual DbSet<Ausencia> Ausencia { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Bonificacion> Bonificacion { get; set; }
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<ClaseHoraExtra> ClaseHoraExtra { get; set; }
        public virtual DbSet<Credencial> Credencial { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<DetalleAporte> DetalleAporte { get; set; }
        public virtual DbSet<DetalleNomina> DetalleNomina { get; set; }
        public virtual DbSet<DetalleRenta> DetalleRenta { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Feriado> Feriado { get; set; }
        public virtual DbSet<FeriadoLaborado> FeriadoLaborado { get; set; }
        public virtual DbSet<HistorialBonificacion> HistorialBonificacion { get; set; }
        public virtual DbSet<HistorialHoraExtra> HistorialHoraExtra { get; set; }
        public virtual DbSet<HistorialPermiso> HistorialPermiso { get; set; }
        public virtual DbSet<HistorialVacaciones> HistorialVacaciones { get; set; }
        public virtual DbSet<HoraExtra> HoraExtra { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Incapacidad> Incapacidad { get; set; }
        public virtual DbSet<Jornada> Jornada { get; set; }
        public virtual DbSet<Liquidacion> Liquidacion { get; set; }
        public virtual DbSet<Nomina> Nomina { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SalarioBrutoMensual> SalarioBrutoMensual { get; set; }
        public virtual DbSet<SesionUsuario> SesionUsuario { get; set; }
        public virtual DbSet<SolicitudHorasExtra> SolicitudHorasExtra { get; set; }
        public virtual DbSet<SolicitudVacaciones> SolicitudVacaciones { get; set; }
        public virtual DbSet<Tardia> Tardia { get; set; }
        public virtual DbSet<TipoCedula> TipoCedula { get; set; }
        public virtual DbSet<TipoIncapacidad> TipoIncapacidad { get; set; }
        public virtual DbSet<TipoLiquidacion> TipoLiquidacion { get; set; }
        public virtual DbSet<TipoPermiso> TipoPermiso { get; set; }
        public virtual DbSet<TramosParametrosRenta> TramosParametrosRenta { get; set; }
        public virtual DbSet<Vacaciones> Vacaciones { get; set; }
        public virtual DbSet<EmpleadoHorario> EmpleadoHorario { get; set; }
        public virtual DbSet<HorarioSemanal> HorarioSemanal { get; set; }
        public virtual DbSet<RegistroMarcacion> RegistroMarcacion { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
    }
}
