//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permiso()
        {
            this.HistorialPermiso = new HashSet<HistorialPermiso>();
        }
    
        public int idPermiso { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public int TipoPermiso_idTipoPermiso { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPermiso> HistorialPermiso { get; set; }
        public virtual TipoPermiso TipoPermiso { get; set; }
    }
}
