//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarioBrutoMensual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalarioBrutoMensual()
        {
            this.DetalleNomina = new HashSet<DetalleNomina>();
        }
    
        public int idSalarioBrutoMensual { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public byte mes { get; set; }
        public int anio { get; set; }
        public decimal salario_bruto { get; set; }
        public System.DateTime fecha_calculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNomina> DetalleNomina { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
