//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarioBrutoMensual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalarioBrutoMensual()
        {
            this.DetalleNomina = new HashSet<DetalleNomina>();
        }
    
        public int idSalarioBrutoMensual { get; set; }
        public int Empleado_idEmpleado { get; set; }
        public byte mes { get; set; }
        public int anio { get; set; }
        public decimal salario_bruto { get; set; }
        public System.DateTime fecha_calculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNomina> DetalleNomina { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
