//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class SesionUsuario
    {
        public int idSesion { get; set; }
        public int Credencial_idCredencial { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string ip { get; set; }
        public string dispositivo { get; set; }
        public bool activo { get; set; }
    
        public virtual Credencial Credencial { get; set; }
    }
}
