//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudVacaciones
    {
        public int idSolicitudVacaciones { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public string estado { get; set; }
        public Nullable<int> aprobado_por { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public int Vacaciones_idVacaciones { get; set; }
    
        public virtual Vacaciones Vacaciones { get; set; }
    }
}
