//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudHorasExtra
    {
        public int idSolicitudHorasExtra { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public string estado { get; set; }
        public Nullable<int> aprobado_por { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public int HoraExtra_idHoraExtra { get; set; }
    
        public virtual HoraExtra HoraExtra { get; set; }
    }
}
