//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tardia
    {
        public int idTardia { get; set; }
        public System.DateTime fecha { get; set; }
        public int minutos { get; set; }
        public bool justificada { get; set; }
        public string observacion { get; set; }
        public int Empleado_idEmpleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
