//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tardia
    {
        public int idTardia { get; set; }
        public System.DateTime fecha { get; set; }
        public int minutos { get; set; }
        public bool justificada { get; set; }
        public string observacion { get; set; }
        public int Empleado_idEmpleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
