//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class TramosParametrosRenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TramosParametrosRenta()
        {
            this.DetalleRenta = new HashSet<DetalleRenta>();
        }
    
        public int idTramosParametrosRenta { get; set; }
        public int anio { get; set; }
        public string tramo { get; set; }
        public decimal limite_inferior { get; set; }
        public decimal limite_superior { get; set; }
        public decimal porcentaje { get; set; }
        public decimal exceso { get; set; }
        public string detalle_tramo { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRenta> DetalleRenta { get; set; }
    }
}
