//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGraduacionNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class TramosParametrosRenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TramosParametrosRenta()
        {
            this.DetalleRenta = new HashSet<DetalleRenta>();
        }
    
        public int idTramosParametrosRenta { get; set; }
        public int anio { get; set; }
        public string tramo { get; set; }
        public decimal limite_inferior { get; set; }
        public decimal limite_superior { get; set; }
        public decimal porcentaje { get; set; }
        public decimal exceso { get; set; }
        public string detalle_tramo { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRenta> DetalleRenta { get; set; }
    }
}
